/**
 * Generates supabase/seed.sql from the existing hard-coded scenario data
 * (src/data/scenarios/*.ts) and rescue team roster (src/data/rescueTeams.ts).
 *
 * This is how "existing hard-coded/mock data" gets moved into Supabase:
 * run this once, then paste/run the output SQL against your Supabase project
 * (SQL Editor or `supabase db execute`). It is idempotent (uses upsert-style
 * ON CONFLICT DO NOTHING per row) so re-running it is safe.
 *
 * Usage: npx tsx scripts/generate-seed-sql.ts > supabase/seed.sql
 */
import { scenarios } from '../src/data/scenarios';
import { initialRescueTeams } from '../src/data/rescueTeams';

function sqlStr(v: string | null | undefined): string {
  if (v === null || v === undefined) return 'NULL';
  return `'${v.replace(/'/g, "''")}'`;
}

function sqlNum(v: number | null | undefined): string {
  if (v === null || v === undefined || Number.isNaN(v)) return 'NULL';
  return String(v);
}

function sqlBool(v: boolean | null | undefined): string {
  if (v === null || v === undefined) return 'NULL';
  return v ? 'true' : 'false';
}

function sqlJson(v: unknown): string {
  return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
}

const lines: string[] = [];
lines.push('-- Auto-generated by scripts/generate-seed-sql.ts — DO NOT edit by hand.');
lines.push('-- Regenerate with: npx tsx scripts/generate-seed-sql.ts > supabase/seed.sql');
lines.push('begin;');
lines.push('');

for (const scenario of Object.values(scenarios)) {
  const m = scenario.meta;
  lines.push(`-- ===== Scenario: ${m.id} =====`);
  lines.push(
    `insert into scenarios (id, name, disaster_type, category, region, state, river_basin_or_fault, last_updated, critical_zones_count, total_hazard_zones, total_relief_centres, total_population_at_risk, total_vulnerable_population, available_shelter_capacity, total_shelter_capacity, total_shelter_occupancy, hazard_icon, hazard_color) values (${sqlStr(
      m.id
    )}, ${sqlStr(m.name)}, ${sqlStr(m.disasterType)}, ${sqlStr(m.category)}, ${sqlStr(m.region)}, ${sqlStr(
      m.state
    )}, ${sqlStr(m.riverBasinOrFault)}, ${sqlStr(m.lastUpdated)}, ${sqlNum(m.criticalZonesCount)}, ${sqlNum(
      m.totalHazardZones
    )}, ${sqlNum(m.totalReliefCentres)}, ${sqlNum(m.totalPopulationAtRisk)}, ${sqlNum(
      m.totalVulnerablePopulation
    )}, ${sqlNum(m.availableShelterCapacity)}, ${sqlNum(m.totalShelterCapacity)}, ${sqlNum(
      m.totalShelterOccupancy
    )}, ${sqlStr(m.hazardIcon)}, ${sqlStr(m.hazardColor)}) on conflict (id) do nothing;`
  );

  for (const z of scenario.riskZones) {
    lines.push(
      `insert into risk_zones (id, scenario_id, name, code, district, river_basin, risk_score, risk_level, priority, population, vulnerable_population, exposure_level, flood_depth_est_meters, water_level_trend, recommended_action, lat, lng, polygon, vulnerability_breakdown, reasoning, last_assessed) values (${sqlStr(
        z.id
      )}, ${sqlStr(m.id)}, ${sqlStr(z.name)}, ${sqlStr(z.code)}, ${sqlStr(z.district)}, ${sqlStr(
        z.riverBasin
      )}, ${sqlNum(z.riskScore)}, ${sqlStr(z.riskLevel)}, ${sqlStr(z.priority)}, ${sqlNum(z.population)}, ${sqlNum(
        z.vulnerablePopulation
      )}, ${sqlStr(z.exposureLevel)}, ${sqlNum(z.floodDepthEstMeters)}, ${sqlStr(z.waterLevelTrend)}, ${sqlStr(
        z.recommendedAction
      )}, ${sqlNum(z.coordinates.lat)}, ${sqlNum(z.coordinates.lng)}, ${sqlJson(z.polygon)}, ${sqlJson(
        z.vulnerabilityBreakdown
      )}, ${sqlStr(z.reasoning)}, ${sqlStr(z.lastAssessed)}) on conflict (id) do nothing;`
    );
  }

  for (const c of scenario.reliefCentres) {
    lines.push(
      `insert into relief_centres (id, scenario_id, name, code, location, lat, lng, capacity, occupancy, available, status, distance_km, travel_time_min, facilities, contact_officer, elevation_meters, safety_score) values (${sqlStr(
        c.id
      )}, ${sqlStr(m.id)}, ${sqlStr(c.name)}, ${sqlStr(c.code)}, ${sqlStr(c.location)}, ${sqlNum(
        c.coordinates.lat
      )}, ${sqlNum(c.coordinates.lng)}, ${sqlNum(c.capacity)}, ${sqlNum(c.occupancy)}, ${sqlNum(
        c.available
      )}, ${sqlStr(c.status)}, ${sqlNum(c.distanceKm)}, ${sqlNum(c.travelTimeMin)}, ${sqlJson(
        c.facilities
      )}, ${sqlJson(c.contactOfficer)}, ${sqlNum(c.elevationMeters)}, ${sqlNum(c.safetyScore)}) on conflict (id) do nothing;`
    );
  }

  for (const r of scenario.evacuationRoutes) {
    lines.push(
      `insert into evacuation_routes (id, scenario_id, origin_id, origin_name, destination_id, destination_name, distance_km, estimated_time_min, safety_score, safety_level, blocked_roads_count, elevation_clearance_meters, coordinates, turn_by_turn, is_recommended) values (${sqlStr(
        r.id
      )}, ${sqlStr(m.id)}, ${sqlStr(r.originId)}, ${sqlStr(r.originName)}, ${sqlStr(r.destinationId)}, ${sqlStr(
        r.destinationName
      )}, ${sqlNum(r.distanceKm)}, ${sqlNum(r.estimatedTimeMin)}, ${sqlNum(r.safetyScore)}, ${sqlStr(
        r.safetyLevel
      )}, ${sqlNum(r.blockedRoadsCount)}, ${sqlNum(r.elevationClearanceMeters)}, ${sqlJson(
        r.coordinates
      )}, ${sqlJson(r.turnByTurn)}, ${sqlBool(r.isRecommended)}) on conflict (id) do nothing;`
    );
  }

  for (const b of scenario.blockedRoads) {
    lines.push(
      `insert into blocked_roads (id, scenario_id, name, reason, coordinates, severity, reported_at) values (${sqlStr(
        b.id
      )}, ${sqlStr(m.id)}, ${sqlStr(b.name)}, ${sqlStr(b.reason)}, ${sqlJson(b.coordinates)}, ${sqlStr(
        b.severity
      )}, ${sqlStr(b.reportedAt)}) on conflict (id) do nothing;`
    );
  }

  for (const rn of scenario.roadNetworks) {
    lines.push(
      `insert into road_networks (id, scenario_id, name, type, status, coordinates, speed_limit_kmh, lanes, elevation_meters) values (${sqlStr(
        rn.id
      )}, ${sqlStr(m.id)}, ${sqlStr(rn.name)}, ${sqlStr(rn.type)}, ${sqlStr(rn.status)}, ${sqlJson(
        rn.coordinates
      )}, ${sqlNum(rn.speedLimitKmh)}, ${sqlNum(rn.lanes)}, ${sqlNum(rn.elevationMeters)}) on conflict (id) do nothing;`
    );
  }

  for (const a of scenario.alerts) {
    lines.push(
      `insert into alerts (id, scenario_id, title, message, severity, timestamp, zone_id, read) values (${sqlStr(
        a.id
      )}, ${sqlStr(m.id)}, ${sqlStr(a.title)}, ${sqlStr(a.message)}, ${sqlStr(a.severity)}, ${sqlStr(
        a.timestamp
      )}, ${sqlStr(a.zoneId)}, ${sqlBool(a.read)}) on conflict (id) do nothing;`
    );
  }

  const d = scenario.demographics;
  lines.push(
    `insert into demographics (scenario_id, total_population_at_risk, total_vulnerable_population, active_hazard_zones_count, critical_zones_count, relief_centres_count, available_shelter_capacity, total_shelter_capacity, total_shelter_occupancy, vulnerability_distribution) values (${sqlStr(
      m.id
    )}, ${sqlNum(d.totalPopulationAtRisk)}, ${sqlNum(d.totalVulnerablePopulation)}, ${sqlNum(
      d.activeHazardZonesCount
    )}, ${sqlNum(d.criticalZonesCount)}, ${sqlNum(d.reliefCentresCount)}, ${sqlNum(
      d.availableShelterCapacity
    )}, ${sqlNum(d.totalShelterCapacity)}, ${sqlNum(d.totalShelterOccupancy)}, ${sqlJson(
      d.vulnerabilityDistribution
    )}) on conflict (scenario_id) do nothing;`
  );

  const an = scenario.analytics;
  lines.push(
    `insert into analytics_snapshots (scenario_id, risk_distribution, risk_trend, zone_comparison, shelter_utilization, evacuation_progress) values (${sqlStr(
      m.id
    )}, ${sqlJson(an.riskDistributionData)}, ${sqlJson(an.riskTrendData)}, ${sqlJson(
      an.zoneComparisonData
    )}, ${sqlJson(an.shelterUtilizationData)}, ${sqlJson(an.evacuationProgressData)}) on conflict (scenario_id) do nothing;`
  );

  lines.push('');
}

lines.push('-- ===== Rescue Teams (shared across scenarios) =====');
for (const t of initialRescueTeams) {
  lines.push(
    `insert into rescue_teams (id, name, specialization, handles, status, base_distance_km, base_eta_min, active_incident_id) values (${sqlStr(
      t.id
    )}, ${sqlStr(t.name)}, ${sqlStr(t.specialization)}, ${sqlJson(t.handles)}, ${sqlStr(t.status)}, ${sqlNum(
      t.baseDistanceKm
    )}, ${sqlNum(t.baseEtaMin)}, ${sqlStr(t.activeIncidentId)}) on conflict (id) do nothing;`
  );
}

lines.push('');
lines.push('commit;');

console.log(lines.join('\n'));
